### ISSUE TITLE
Using 1.6.0 with VS2010 fails

### ISSUE THREAD

**Issue by dconnet** [unittest-cpp/unittest-cpp#107]
Build the library (as a static library) is fine. However, when using it, all my test files fail with:
1>  TestArchive.cpp
1>c:\winsrc\libraries\unittest++\src\RequiredCheckTestReporter.h(26): error C2220: warning treated as error - no 'object' file generated
1>c:\winsrc\libraries\unittest++\src\RequiredCheckTestReporter.h(26): warning C4512: 'UnitTest::RequiredCheckTestReporter' : assignment operator could not be generated
1>          c:\winsrc\libraries\unittest++\src\RequiredCheckTestReporter.h(14) : see declaration of 'UnitTest::RequiredCheckTestReporter'

(yes, I have warnings as errors turned on)

The same code builds fine on vs2015.

**Comment by pjohnmeyer** [comment]
Thanks. Building the library probably operates at a different warning level than your project, because CMake doesn't default to such a high warning level. This is related to #10, in which I'd like to crank up the warning level (and turn on warnings as errors) for the project as a whole.

Regardless we surely want to keep at least the headers clean for just this reason. Happy to entertain a pull request with a fix (preferably one that addresses the warning rather than disabling it).

**Comment by dconnet** [comment]
I compile at level 4, warnings-as-errors. It seems an assignment operator is not needed - so disabling the warning allowed my tests to compile and perform as expected. I disable only on vc10 and lower. (untested on vc11/12)

A 'diff -c' of that:
```
*** RequiredCheckTestReporter.h.orig	Tue Apr 05 17:19:20 2016
--- RequiredCheckTestReporter.h	Tue Apr 05 06:56:56 2016
***************
*** 4,9 ****
--- 4,14 ----
  #include "HelperMacros.h"
  #include "ThrowingTestReporter.h"
  
+ #if defined(_MSC_VER) && _MSC_VER <= 1600
+ #pragma warning(push)
+ #pragma warning(disable : 4512)
+ #endif
+ 
  namespace UnitTest {
  
     class TestResults;
***************
*** 26,30 ****
--- 31,38 ----
     };
  }
  
+ #if defined(_MSC_VER) && _MSC_VER <= 1600
+ #pragma warning(pop)
  #endif
  
+ #endif
```
