### ISSUE TITLE
Unresolved link errors in VS 2015

### ISSUE THREAD

**Issue by jamesjohnmcguire** [unittest-cpp/unittest-cpp#118]
I found the following after refreshing one of my projects:
Error	LNK2019	unresolved external symbol "public: virtual __thiscall UnitTest::RequiredCheckException::~RequiredCheckException(void)" (??1RequiredCheckException@UnitTest@@UAE@XZ) referenced in function "public: virtual void * __thiscall UnitTest::RequiredCheckException::`vector deleting destructor'(unsigned int)" (??_ERequiredCheckException@UnitTest@@UAEPAXI@Z)	unittestpp_vs2008	Test.obj
Error	LNK1120	1 unresolved externals	unittestpp_vs2008

I was able to work-around this by adding RequiredCheckException.cppp & RequiredCheckException.h to the actual solution.

Afterwards, it would compile and link.  However, I get the following warning:

Warning	MSB8012	TargetName(unittestpp_vs2008) does not match the Linker's OutputFile property value (unittestpp). This may cause your project to build incorrectly. To correct this, please make sure that $(OutDir), $(TargetName) and $(TargetExt) property values match the value specified in %(Link.OutputFile).	unittestpp_vs2008	C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V120\Microsoft.CppBuild.targets	1195	

That's certainly livable and not urgent.

**Comment by pjohnmeyer** [comment]
Can you please explain what you mean by "refreshing one of my projects"? I cannot reproduce this error.

Thanks!

**Comment by jamesjohnmcguire** [comment]
This happened a while ago, so my recollection may not be perfect.  But, I believe, I meant 'nuget Update-Package'.

In the first part. the files mentioned, did exist but they were not part of the .csproj, if I recall correctly.

Let me know if you would like additional information.

**Comment by pjohnmeyer** [comment]
UnitTest++ does not currently have a nuget package ( see #81 ) so if somebody is bundling it in, I don't know how they are doing so. Sorry I didn't get my questions to you while it was fresh.

The only theory I have off the top of my head is that, since we use file-globbing, CMake does not detect any changes when a file is added -- so the normally dependency checking of CMake doesn't kick in.

> (We do not recommend using GLOB to collect a list of source files from your source tree. If no CMakeLists.txt file changes when a source is added or removed then the generated build system cannot know when to ask CMake to regenerate.)
-- https://cmake.org/cmake/help/v3.0/command/file.html

They may not recommend it, but it's the simplest way to maintain so myself and a lot of other projects do it this way -- and it's incredibly easy to just re-run CMake after an update.

Unless you can dredge up some memories or reproduce this, I'm going to close the issue for now.

**Comment by jamesjohnmcguire** [comment]
Ah, yes.  Let me correct myself.  I did an svn up (which actually does a git pull) from https://github.com/unittest-cpp/unittest-cpp/trunk.  I should have also noted from the beginning that I'm building this with Visual Studio 2015 Community IDE.

Since CMake is noted as a prerequisite, leaving this closed is fine with me.
