### ISSUE TITLE
Migrate and update existing documentation from SourceForge

### ISSUE THREAD

**Issue by pjohnmeyer** [unittest-cpp/unittest-cpp#6]
http://unittest-cpp.sourceforge.net/
http://unittest-cpp.sourceforge.net/UnitTest++.html
http://unittest-cpp.sourceforge.net/money_tutorial/

**Comment by mletterle** [comment]
Sourceforge site is down now, BTW, still available in the wayback machine but....

**Comment by grahamreeds** [comment]
I had briefly worked on this. I will pick it up again.

GR

**Comment by grahamreeds** [comment]
I made a pass for the version I forked about a year ago - lucky because I couldn't find it on my machine.

https://github.com/grahamreeds/unittest-cpp/wiki/Money,-a-step-by-step-example-for-Visual-Studio-2013

If you give me write access I will change it for the CMake world or you can take it and drop it in.  It is no where near complete and no images but it is better than nothing.

**Comment by pjohnmeyer** [comment]
I heavily updated wiki docs tonight and I am closing this as a result. It isn't a direct port over of the old docs, and there is always more that can be written, but I think it is sufficient.
